---
- name: node-exporters
  hosts: node_exporters
  remote_user: root
  # key_file: ~/.ssh/id_rsa
  gather_facts: false
  roles:
    - node-exporter
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: ping
      ping:
